# LevelPlayers
# Author: IrukaMine
# Version: 1.4.0
# Placeholder to display level %levelplayers_level%
# Placeholder to display specific level %levelplayers_level_<level>%

# Basic settings
settings:
  language: "English" # Available languages: English, Russian, Ukrainian, Polish, Chinese, French, Spanish

# Database settings
database:
  enabled: true  # If false, will use YAML file storage instead of SQLite

# Level system settings
level-settings:
  max-level: 5  # Maximum level
  format: "&7Level &6%level%" # Default format for unconfigured levels
  
levels:
  1: "&7Level &6I"
  2: "&7Level &6II"
  3: "&7Level &6III"
  4: "&7Level &6IV"
  5: "&7Level &6V"
  #...