name: LevelPlayers
version: '1.4.0'
main: com.example.LevelPlayers
api-version: '1.18'
description: Плагин для управления уровнями игроков
author: IrukaMine
website: https://iruka-shop.site/
depend: [PlaceholderAPI]

commands:
  level:
    description: Установить уровень игрока
    usage: /<command> <игрок> <уровень>
    aliases: [lvl]
  levelplayers:
    description: Команды управления плагином
    usage: /<command> reload
    aliases: [lp]

permissions:
  levelplayers.set:
    description: Позволяет устанавливать уровни игрокам
    default: op
  levelplayers.reload:
    description: Позволяет перезагружать плагин
    default: op
  levelplayers.give:
    description: Позволяет повышать уровень игрока
    default: op
  levelplayers.take:
    description: Позволяет понижать уровень игрока
    default: op